### ISSUE TITLE
Blender avatar not receiving data.

### ISSUE THREAD

**Issue by delebash** [NumesSanguis/FACSvatar-Blender#3]
System Info:
Windows 10 x64  v1909
FACSvatar v0.4.0
FACSvatar-blender v0_4_0-alpha
Blender v2.82a
MB-Lab v1.7.7

I have FACSvatar up and running via the Docker for Windows directions.  I am using the webcam version and I can see the data sent from OpenFaceOffline.exe to my Docker container ip address 127.0.0.1. I  have the openface_2.1.0_zeromq\config.xml set to ip = 127.0.0.1 port =5570

Below is my docker container info when I run `docker-compose up`.

Attaching to modules_facsvatar_facsfromcsv_1, modules_facsvatar_facstoblend_1, modules_facsvatar_bridge_1
facsvatar_facsfromcsv_1  | tail: cannot open 'anything' for reading: No such file or directory
facsvatar_facstoblend_1  | INFO:root:Current libzmq version is 4.2.5
facsvatar_facstoblend_1  | INFO:root:Current  pyzmq version is 17.1.2
facsvatar_facstoblend_1  | INFO:root:Publisher port is specified
facsvatar_facstoblend_1  | INFO:root:Creating ZeroMQ context on: tcp://*:5572
facsvatar_facstoblend_1  | INFO:root:Bind to tcp://*:5572 successful
facsvatar_facstoblend_1  | INFO:root:Write timestamps to: logging/timestamps_pub.csv
facsvatar_facstoblend_1  | INFO:root:Publisher socket set-up complete
facsvatar_facstoblend_1  | INFO:root:Subscriber port is specified
facsvatar_facstoblend_1  | INFO:root:Creating ZeroMQ context on: tcp://facsvatar_bridge:5571
facsvatar_facstoblend_1  | INFO:root:Connect to tcp://facsvatar_bridge:5571 successful
facsvatar_facstoblend_1  | INFO:root:Write timestamps to: logging/timestamps_sub.csv
facsvatar_facstoblend_1  | INFO:root:Subscriber socket set-up complete
facsvatar_facstoblend_1  | INFO:root:deal_port not specified, not setting-up dealer
facsvatar_facstoblend_1  | INFO:root:deal2_port not specified, not setting-up dealer
facsvatar_facstoblend_1  | INFO:root:deal3_port not specified, not setting-up dealer
facsvatar_facstoblend_1  | INFO:root:rout_port not specified, not setting-up router
facsvatar_facstoblend_1  | INFO:root:ZeroMQ sockets successfully set-up
facsvatar_facstoblend_1  |
facsvatar_bridge_1       | INFO:root:Current libzmq version is 4.2.5
facsvatar_bridge_1       | INFO:root:Current  pyzmq version is 17.1.2
facsvatar_bridge_1       | INFO:root:Publisher port is specified
facsvatar_bridge_1       | INFO:root:Creating ZeroMQ context on: tcp://*:5571
facsvatar_bridge_1       | INFO:root:Bind to tcp://*:5571 successful
facsvatar_bridge_1       | INFO:root:Write timestamps to: logging/timestamps_pub.csv
facsvatar_bridge_1       | INFO:root:Publisher socket set-up complete
facsvatar_bridge_1       | INFO:root:Subscriber port is specified
facsvatar_bridge_1       | INFO:root:Creating ZeroMQ context on: tcp://*:5570
facsvatar_bridge_1       | INFO:root:Bind to tcp://*:5570 successful
facsvatar_bridge_1       | INFO:root:Write timestamps to: logging/timestamps_sub.csv
facsvatar_bridge_1       | INFO:root:Subscriber socket set-up complete
facsvatar_bridge_1       | INFO:root:deal_port not specified, not setting-up dealer
facsvatar_bridge_1       | INFO:root:deal2_port not specified, not setting-up dealer
facsvatar_bridge_1       | INFO:root:deal3_port not specified, not setting-up dealer
facsvatar_bridge_1       | INFO:root:Router port is specified
facsvatar_bridge_1       | INFO:root:Creating ZeroMQ context on: tcp://127.0.0.1:5580
facsvatar_bridge_1       | INFO:root:Bind to tcp://127.0.0.1:5580 successful
facsvatar_bridge_1       | INFO:root:Router socket set-up complete
facsvatar_bridge_1       | INFO:root:ZeroMQ sockets successfully set-up
facsvatar_bridge_1       |
facsvatar_bridge_1       | INFO:root:Awaiting FACS data...

The FACSvatar-Blender add-on ip address is set to 127.0.0.1  I have tried ports 5570, 5571, 5572, 5580 but I do not see the avatar moving.  I noticed in your instructions video that in the  add-on you have your port set to 5572.  As mentioned I tried that still no joy.

Any ideas?

Thanks
Dan

**Comment by NumesSanguis** [comment]
Are you using `docker-compose.yml` or `docker-compose_filter.yml`? If you're using `_filter` than the port should be `5573`. Although from the output it seems you're using `docker-compose.yml`, so `5572` should be correct.

Just to confirm:
- After you start tracking in OpenFace, the Docker containers receives data (there is output printed after `facsvatar_bridge_1 | INFO:root:Awaiting FACS data...`)?
- The MB-Lab character is finalized (it has Shape Keys to move the facial expressions)
- The MB-Lab avatar is selected?

Can you start Blender with a terminal (e.g. PowerShell / Anaconda Prompt, etc), and see if you see data being send into this terminal?.
Likely you can do that with commands similar to:

```
Double click on: C:\Program Files\Blender Foundation\Blender 2.82\blender_debug_log.cmd
```
or
```
cd C:\Program Files\Blender Foundation\Blender 2.82
.\blender.exe
```

**Comment by delebash** [comment]
Works great when you actually select the avatar.  Sorry for the mistake and thank you very much for your help!!

**Comment by NumesSanguis** [comment]
Great to hear your problem was solved :) Please give me an update if you make a video or something!
