### ISSUE TITLE
Key Frame capture from prerecorded video streamed from OpenFace to FACSvatar-Blender is not working in some scenarios

### ISSUE THREAD

**Issue by Hunanbean** [NumesSanguis/FACSvatar-Blender#4]
Key frame capture seems to only work if you do not have the OpenFace program open when you click Connect Socket, and Insert Key Frame in the FACSvatar-Blender plugin.

As long as you set Connected, and Insert Key Frames before you open OpenFace, it captures key frames successfully. If you have the OpenFace program open, even just idling, when you set these parameters in the FACSVatar_Blender plugin, although the avatar moves from the information being streamed, no key frames are captured.

**Comment by NumesSanguis** [comment]
Thank you for making this issue. I see you reported the same issue here, but with more details: https://github.com/NumesSanguis/FACSvatar/issues/23

I'll update the progress of this issue over there.

**Comment by Hunanbean** [comment]
Ah. appears i did a double post instead of an edit. thanks for catching it!
